import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>)
{
  return (
    <html lang="en">
      <body>
        <p className={"font-centgoth"}>
          this is like a global page, doesn't rerender and applies to all things in this path (think) this layout specifically is a root layout, at the base of the app directory
        </p>
        <div>{children}</div>
      </body>
    </html>
  );
}
