import type { Metadata } from "next";
import localFontCenturyGothic from "next/font/local"
import "./globals.css";

const centuryGothic = localFontCenturyGothic({
  src: [
    {
      path: "./fonts/centurygothic.ttf",
      style: "normal"
    },
    {
      path: "./fonts/centurygothic_bold.ttf",
      style: "bold"
    }
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={centuryGothic.className}>
      <body>{children}</body>
    </html>
  );
}
